---
deployment:
  tasks:
    - export REPOPATH=/var/www/u0102465/repositories/garnizonbaikal/
    - export SITEPATH=/var/www/u0102465/public_html/
    - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH